Fix env variables in breeze env
Fix env variables in breeze env

diff --git a/.github/workflows/fabric-provider-tests.yml b/.github/workflows/fabric-provider-tests.yml
--- a/.github/workflows/fabric-provider-tests.yml
+++ b/.github/workflows/fabric-provider-tests.yml
@@ -50,34 +50,34 @@ jobs:
           SYSTEM_TESTS_FABRIC_REFRESH_TOKEN: "${{ secrets.REFRESH_TOKEN }}"
           SYSTEM_TESTS_FABRIC_TENANT_ID: "${{ secrets.TENANT_ID }}"
         run: |
-          breeze shell << EOF
-          printenv
-          pytest tests/system/providers/microsoft/fabric/example_fabric_item_run.py \
+          export BREEZE_INIT_COMMAND="export SYSTEM_TESTS_FABRIC_CLIENT_ID=${SYSTEM_TESTS_FABRIC_CLIENT_ID} \
+            && export SYSTEM_TESTS_FABRIC_REFRESH_TOKEN=${SYSTEM_TESTS_FABRIC_REFRESH_TOKEN} \
+            && export SYSTEM_TESTS_FABRIC_TENANT_ID=${SYSTEM_TESTS_FABRIC_TENANT_ID}"
+
+          printenv SYSTEM_TESTS_FABRIC_CLIENT_ID
+
+          breeze testing tests \
+          tests/system/providers/microsoft/fabric/example_fabric_notebook_run.py \
+          tests/system/providers/microsoft/fabric/example_fabric_pipeline_run.py \
           tests/system/providers/microsoft/fabric/example_mock_system_test.py \
           --system microsoft \
           --junitxml=tests/pytest-report.xml
-          EOF
-# breeze testing tests \
-# tests/system/providers/microsoft/fabric/example_fabric_item_run.py \
-# tests/system/providers/microsoft/fabric/example_mock_system_test.py \
-# --system microsoft \
-# --junitxml=tests/pytest-report.xml
 
-      - name: Upload Raw System Test Report to Github artifact storage
-        uses: actions/upload-artifact@v3
-        if: success() || failure()
-        with:
-          name: pytest-report
-          path: tests/pytest-report.xml  # path of the file to upload
+      # - name: Upload Raw System Test Report to Github artifact storage
+      #   uses: actions/upload-artifact@v3
+      #   if: success() || failure()
+      #   with:
+      #     name: pytest-report
+      #     path: tests/pytest-report.xml  # path of the file to upload
 
-      - name: Upload System Test report to Azure Blob storage
-        uses: fixpoint/azblob-upload-artifact@v4
-        if: success() || failure()
-        with:
-          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
-          name: pytest-report.xml
-          container: airflow-system-dashboard-input
-          path: tests/pytest-report.xml
+      # - name: Upload System Test report to Azure Blob storage
+      #   uses: fixpoint/azblob-upload-artifact@v4
+      #   if: success() || failure()
+      #   with:
+      #     connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
+      #     name: pytest-report.xml
+      #     container: airflow-system-dashboard-input
+      #     path: tests/pytest-report.xml
 
 # preprocess:
 #   runs-on: ubuntu-latest
