Dev: CopyArtifactToGithubPageRepo

diff --git a/.github/workflows/fabric-provider-tests.yml b/.github/workflows/fabric-provider-tests.yml
--- a/.github/workflows/fabric-provider-tests.yml
+++ b/.github/workflows/fabric-provider-tests.yml
@@ -71,62 +71,62 @@ jobs:
   #         container: airflow-system-dashboard-input
   #         path: tests/pytest-report.xml
 
-  preprocess:
-    runs-on: ubuntu-latest
-    env:
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
-      REPO_OWNER: ${{ github.repository_owner }}
-      REPO_NAME: ${{ github.repository }}
-      GITHUB_RUN_ID: ${{ github.run_id }}
-    # needs: rebase  # This job runs only after the 'check-artifact' job completes (success or failure)
-    if: success() || failure()
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v3
-        with:
-          token: ${{ secrets.AIRFLOW_FORK_TOKEN }}
-          persist-credentials: false
+  # preprocess:
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
+  #     REPO_OWNER: ${{ github.repository_owner }}
+  #     REPO_NAME: ${{ github.repository }}
+  #     GITHUB_RUN_ID: ${{ github.run_id }}
+  #   # needs: rebase  # This job runs only after the 'check-artifact' job completes (success or failure)
+  #   if: success() || failure()
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v3
+  #       with:
+  #         token: ${{ secrets.AIRFLOW_FORK_TOKEN }}
+  #         persist-credentials: false
 
-      - name: Set Up Git
-        run: |
-          git config --global user.name "Ambika Garg"
-          git config --global user.email "ambikagarg1101@gmail.com"
+  #     - name: Set Up Git
+  #       run: |
+  #         git config --global user.name "Ambika Garg"
+  #         git config --global user.email "ambikagarg1101@gmail.com"
 
-      # - name: Download artifact
-      #   uses: actions/download-artifact@v3
-      #   with:
-      #     name: pytest-report
-      #     path: pytest-report
+  #     # - name: Download artifact
+  #     #   uses: actions/download-artifact@v3
+  #     #   with:
+  #     #     name: pytest-report
+  #     #     path: pytest-report
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.10'
+  #     - name: Set up Python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: '3.10'
 
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install azure-storage-blob azure-identity
+  #     - name: Install dependencies
+  #       run: |
+  #         python -m pip install --upgrade pip
+  #         pip install azure-storage-blob azure-identity
 
-      # - name: Apply preprocessing to the report generated and store in output container
-      #   run: |
-      #     python .github/scripts/process_artifact.py
+  #     # - name: Apply preprocessing to the report generated and store in output container
+  #     #   run: |
+  #     #     python .github/scripts/process_artifact.py
 
-      - name: Get Last k runs and consolidate
-        run: |
-          python .github/scripts/get_last_10_runs.py
+  #     - name: Get Last k runs and consolidate
+  #       run: |
+  #         python .github/scripts/get_last_10_runs.py
       
-      - name: Upload consolidate report as artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: consolidate-report
-          path: consolidate-blob/report.json
+  #     - name: Upload consolidate report as artifact
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: consolidate-report
+  #         path: consolidate-blob/report.json
 
 
   Display-System-Tests:
     runs-on: ubuntu-latest
-    needs: preprocess
+    # needs: preprocess
     if: success()
     steps:
       - name: Checkout Repository
@@ -135,18 +135,20 @@ jobs:
           token: ${{ secrets.AIRFLOW_FORK_TOKEN }}
           persist-credentials: false
 
-      - name: Download artifact
-        uses: actions/download-artifact@v3
+      - name: Download artifact from Azure Blob Storage
+        uses: fixpoint/azblob-download-artifact@v3
         with:
-          name: consolidate-report
-          path: consolidate-report
+          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
+          name: report.json
+          container: consolidate-blob
+          path: consolidate-report/report.json
       
       - name: Push Test file to dashboard repo
         uses: dmnemec/copy_file_to_another_repo_action@main
         env:
           API_TOKEN_GITHUB: ${{ secrets.AIRFLOW_FORK_TOKEN }}
         with:
-          source_file: 'consolidate-report/temp.json'
+          source_file: 'consolidate-report/report.json'
           destination_repo: 'ambika-garg/fabric-airflow-system-dashboard'
           destination_folder: '_data'
           user_email: 'ambikagarg1101@gmail.com'
