Dev: CopyArtifactToGithubPageRepo

diff --git a/.github/workflows/fabric-provider-tests.yml b/.github/workflows/fabric-provider-tests.yml
--- a/.github/workflows/fabric-provider-tests.yml
+++ b/.github/workflows/fabric-provider-tests.yml
@@ -71,56 +71,56 @@ jobs:
   #         container: airflow-system-dashboard-input
   #         path: tests/pytest-report.xml
 
-  preprocess:
-    runs-on: ubuntu-latest
-    env:
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
-      REPO_OWNER: ${{ github.repository_owner }}
-      REPO_NAME: ${{ github.repository }}
-      GITHUB_RUN_ID: ${{ github.run_id }}
-    # needs: rebase  # This job runs only after the 'check-artifact' job completes (success or failure)
-    if: success() || failure()
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v3
-        with:
-          token: ${{ secrets.AIRFLOW_FORK_TOKEN }}
-          persist-credentials: false
+  # preprocess:
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
+  #     REPO_OWNER: ${{ github.repository_owner }}
+  #     REPO_NAME: ${{ github.repository }}
+  #     GITHUB_RUN_ID: ${{ github.run_id }}
+  #   # needs: rebase  # This job runs only after the 'check-artifact' job completes (success or failure)
+  #   if: success() || failure()
+  #   steps:
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@v3
+  #       with:
+  #         token: ${{ secrets.AIRFLOW_FORK_TOKEN }}
+  #         persist-credentials: false
 
-      - name: Set Up Git
-        run: |
-          git config --global user.name "Ambika Garg"
-          git config --global user.email "ambikagarg1101@gmail.com"
+  #     - name: Set Up Git
+  #       run: |
+  #         git config --global user.name "Ambika Garg"
+  #         git config --global user.email "ambikagarg1101@gmail.com"
 
-      # - name: Download artifact
-      #   uses: actions/download-artifact@v3
-      #   with:
-      #     name: pytest-report
-      #     path: pytest-report
+  #     # - name: Download artifact
+  #     #   uses: actions/download-artifact@v3
+  #     #   with:
+  #     #     name: pytest-report
+  #     #     path: pytest-report
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.10'
+  #     - name: Set up Python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: '3.10'
 
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install azure-storage-blob azure-identity
+  #     - name: Install dependencies
+  #       run: |
+  #         python -m pip install --upgrade pip
+  #         pip install azure-storage-blob azure-identity
 
-      # - name: Apply preprocessing to the report generated and store in output container
-      #   run: |
-      #     python .github/scripts/process_artifact.py
+  #     # - name: Apply preprocessing to the report generated and store in output container
+  #     #   run: |
+  #     #     python .github/scripts/process_artifact.py
 
-      - name: Get Last k runs and consolidate
-        run: |
-          python .github/scripts/get_last_10_runs.py
+  #     - name: Get Last k runs and consolidate
+  #       run: |
+  #         python .github/scripts/get_last_10_runs.py
 
 
   CopyArtifactToGithubPageRepo:
     runs-on: ubuntu-latest
-    needs: preprocess
+    # needs: preprocess
     if: success()
     steps:
       - name: Checkout Repository
@@ -147,6 +147,8 @@ jobs:
 
       - name: Copy generated file to target repository
         run: |
+          pwd
+          ls /home/runner
           git branch
           git checkout -b temp
           git remote -v
