Dev: Rebase

diff --git a/.github/workflows/rebase.yml b/.github/workflows/rebase.yml
--- a/.github/workflows/rebase.yml
+++ b/.github/workflows/rebase.yml
@@ -83,18 +83,18 @@ jobs:
       #     name: test-reports
       #     path: test-report
 
-  check-artifact:
-    runs-on: ubuntu-latest
-    needs: rebase  # This job runs only after the 'test' job completes (success or failure)
-    if: success() || failure()
-    steps:
-      - name: Check if artifact exists
-        id: artifact_check
-        run: |
-          if [[ ! -f pytest-report/pytest-report.xml ]]; then
-            echo "Artifact does not exist"
-            exit 1
-          fi
+  # check-artifact:
+  #   runs-on: ubuntu-latest
+  #   needs: rebase  # This job runs only after the 'test' job completes (success or failure)
+  #   if: success() || failure()
+  #   steps:
+  #     - name: Check if artifact exists
+  #       id: artifact_check
+  #       run: |
+  #         if [[ ! -f pytest-report/pytest-report.xml ]]; then
+  #           echo "Artifact does not exist"
+  #           exit 1
+  #         fi
 
   process:
     runs-on: ubuntu-latest
@@ -104,7 +104,8 @@ jobs:
       REPO_OWNER: ${{ github.repository_owner }}
       REPO_NAME: ${{ github.repository }}
       GITHUB_RUN_ID: ${{ github.run_id }}
-    needs: check-artifact  # This job runs only after the 'check-artifact' job completes (success or failure)
+    needs: rebase  # This job runs only after the 'check-artifact' job completes (success or failure)
+    if: success() || failure()
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
@@ -115,8 +116,8 @@ jobs:
       - name: Download artifact
         uses: actions/download-artifact@v3
         with:
-          name: test-report
-          path: test-report
+          name: pytest-report
+          path: pytest-report
       
       - name: Set up Python
         uses: actions/setup-python@v4
