Dev: Rebase

diff --git a/.github/workflows/rebase.yml b/.github/workflows/rebase.yml
--- a/.github/workflows/rebase.yml
+++ b/.github/workflows/rebase.yml
@@ -83,6 +83,19 @@ jobs:
       #     name: test-reports
       #     path: test-report
 
+  check-artifact:
+    runs-on: ubuntu-latest
+    needs: rebase  # This job runs only after the 'test' job completes (success or failure)
+    if: success() || failure()
+    steps:
+      - name: Check if artifact exists
+        id: artifact_check
+        run: |
+          if [[ ! -f pytest-report ]]; then
+            echo "Artifact does not exist"
+            exit 1
+          fi
+
   process:
     runs-on: ubuntu-latest
     env:
@@ -91,7 +104,7 @@ jobs:
       REPO_OWNER: ${{ github.repository_owner }}
       REPO_NAME: ${{ github.repository }}
       GITHUB_RUN_ID: ${{ github.run_id }}
-    needs: rebase
+    needs: check-artifact  # This job runs only after the 'check-artifact' job completes (success or failure)
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
